[package]
name = "uniswap-sdk-core-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clippy = "0.0.302"
eth_checksum = "0.1.2"
lazy_static = "1.4.0"
num-bigint = "0.4.4"
num-integer = "0.1.45"
num-rational = "0.4.1"
num-traits = "0.2.17"
rust_decimal = "1.33.1"
rustc-hex = "2.1.0"
serde-value = "0.7.0"
